fix: post signup
CA-G12/car-trade pull request #100
Opened 2022-10-26 13:11 UTC by abdou059

2022-10-26 13:24 UTC, LinaYahya requested changes

2022-10-26 13:24 UTC, LinaYahya commented on .vscode/settings.json
> +  ]
```suggestion

```

2022-10-26 13:24 UTC, LinaYahya commented on server/src/validation/signupSchema.ts
> +    .required(),
Where `fullName`, and `phoneNumber` validation messages?

2022-10-26 13:24 UTC, LinaYahya commented on server/src/services/checkEmail.ts
> +  const gtiEmail = await Customer.findAll({
```suggestion
  const getEmail = await Customer.findAll({
```

2022-10-26 13:24 UTC, LinaYahya commented on server/src/controllers/signup.ts
> +    throw createError(400, 'this email is signup');
```suggestion
    throw createError(400, 'this email is signup'); 
```
use a clear message

2022-10-26 13:24 UTC, LinaYahya commented on server/src/controllers/signup.ts
> +  const res = await signupUser({
```suggestion
  const user = await signupUser({
```

2022-10-26 13:24 UTC, LinaYahya commented on server/src/controllers/signup.ts
> +  const token = await generateToken({ userId: res, role: 'user' });
is `res` is really the useId, try to console `res`, to figure what is it?

2022-10-26 13:24 UTC, LinaYahya commented on server/src/controllers/signup.ts
> +  return { status: 200, msg: 'done!', data: token };
```suggestion
  return { status: 201, msg: 'done!', data: token };
```

2022-10-26 13:24 UTC, LinaYahya commented on server/src/controllers/signup.ts
> +  return { status: 200, msg: 'done!', data: token };
Also check the return structure How should it be

2022-10-26 18:15 UTC, LinaYahya requested changes

2022-10-26 18:15 UTC, LinaYahya commented on server/src/controllers/signup.ts
> +  return { status: 201, msg: 'done!', data: token };
```suggestion
  return { status: 201, msg: 'done!', data: token };
```
data is not token, check `expressWrapper`

2022-10-27 04:21 UTC, mai-mohammed requested changes

2022-10-27 04:21 UTC, mai-mohammed commented on server/__tests__/cars.ts
> +  });
if possible write tests for more conditions.

2022-10-27 04:21 UTC, mai-mohammed commented on server/src/controllers/signup.ts
> +    throw createError(400, 'this email is registered');
just return it and put the error in the returned object

2022-10-27 06:31 UTC, husamkamal commented on server/src/controllers/signup.ts
> +  if (result.length) {
add not 1

2022-10-27 07:01 UTC, mai-mohammed approved these changes

2022-10-27 07:02 UTC, mai-mohammed approved these changes

2022-10-27 07:03 UTC, husamkamal approved these changes

2022-10-27 07:48 UTC, LinaYahya approved these changes

2022-10-27 07:52 UTC, tariqabusada approved these changes

2022-10-27 08:07 UTC, merged