106 admin login
CA-G12/car-trade pull request #107
Opened 2022-10-27 09:08 UTC by abdou059

2022-10-27 10:03 UTC, husamkamal commented on client/src/pages/AdminLogin/index.tsx
> +      const login = async () => {
remove the auth/login to admin endpoint

2022-10-27 10:25 UTC, LinaYahya requested changes

2022-10-27 10:25 UTC, LinaYahya commented on client/src/helpers/validationSchema.ts
> +const AdminLoginSchema = yup.object({
What about password?

2022-10-27 10:25 UTC, LinaYahya commented on client/src/helpers/validationSchema.ts
> +  userName: yup
```suggestion
  username: yup
```

2022-10-27 10:25 UTC, LinaYahya commented on client/src/pages/AdminLogin/index.tsx
> +      UserName: '',
```suggestion
      Username: '',
```

2022-10-27 10:25 UTC, LinaYahya commented on client/src/pages/AdminLogin/index.tsx
> +            id="outlined-basic"
Why there's no value for username

2022-10-28 13:22 UTC, LinaYahya requested changes

2022-10-28 13:22 UTC, LinaYahya commented on client/src/pages/AdminLogin/index.tsx
> +            id="outlined-basic"
and onChange and error, helper text?

2022-10-29 18:24 UTC, LinaYahya requested changes

2022-10-29 18:24 UTC, LinaYahya commented on client/src/pages/AdminLogin/index.tsx
> +      const Admin = async () => {
```suggestion
      const Admin = async () => {
```
Not sure what function name means?

2022-10-29 18:24 UTC, LinaYahya commented on client/src/pages/AdminLogin/index.tsx
> +          console.log(result);
```suggestion
```

2022-10-29 18:24 UTC, LinaYahya commented on client/src/pages/AdminLogin/index.tsx
> +          setResponseError('error');
```suggestion
          setResponseError('error'); // IS that a clear and understood error message?
```

2022-10-30 00:07 UTC, mai-mohammed approved these changes

2022-10-30 09:49 UTC, tariqabusada commented on client/src/pages/AdminLogin/index.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
no need to unused variables so we don't need the 'disable' comment

2022-10-30 10:25 UTC, husamkamal approved these changes

2022-10-30 10:32 UTC, LinaYahya requested changes

2022-10-30 10:32 UTC, LinaYahya commented on client/src/pages/AdminLogin/index.tsx
> +      const AdminInfo = async () => {
not sure why you create a function inside onSubmit, either to create a function outside the component or to just call request outside of function

2022-10-30 10:32 UTC, LinaYahya commented on client/src/pages/AdminLogin/index.tsx
> +            responseError
try to set response error after reset or update form values

2022-10-30 18:14 UTC, LinaYahya approved these changes

2022-10-31 07:34 UTC, tariqabusada approved these changes

2022-10-31 07:34 UTC, merged