112 profile
CA-G12/car-trade pull request #113
Opened 2022-10-28 13:31 UTC by husamkamal

2022-10-29 18:25 UTC, LinaYahya requested changes
Delete unrelated changes

2022-10-30 07:59 UTC, mai-mohammed approved these changes

2022-10-30 08:13 UTC, abdou059 approved these changes

2022-10-30 11:01 UTC, LinaYahya approved these changes

2022-10-30 12:29 UTC, merged