108 admin login back
CA-G12/car-trade pull request #117
Opened 2022-10-28 19:27 UTC by abdou059

2022-10-29 10:59 UTC, husamkamal requested changes
why you push all admin login front and back together there is anther pull request that have front

2022-10-29 18:40 UTC, LinaYahya requested changes
delete unrelated changes, So I can review the code,
Also please take care of commit messages as it doesn't make sense to have three commits with the same message

2022-10-30 06:40 UTC, LinaYahya requested changes

2022-10-30 06:40 UTC, LinaYahya commented on server/src/services/auth.ts
> +  const getAdmin:any = await Admin.findOne({
```suggestion
  const getAdmin:any = await Admin.findOne({ 
```
remove any from here, and it's not a function to have an action name

2022-10-30 07:09 UTC, LinaYahya requested changes

2022-10-30 07:09 UTC, LinaYahya commented on server/src/services/auth.ts
> +  const findAdmin:any = await Admin.findOne({
```suggestion
  const admin = await Admin.findOne({
```

2022-10-30 07:09 UTC, LinaYahya commented on server/src/controllers/auth.ts
> +const AdminLogin = async (req:Request) => {
```suggestion
const loginAdmin = async (req:Request) => {
```

2022-10-30 07:24 UTC, mai-mohammed approved these changes

2022-10-30 08:15 UTC, LinaYahya approved these changes

2022-10-30 08:20 UTC, husamkamal approved these changes

2022-10-30 08:50 UTC, tariqabusada approved these changes

2022-10-30 08:51 UTC, merged