build: tests for add new selling request in most use cases
CA-G12/car-trade pull request #122
Opened 2022-10-29 12:54 UTC by tariqabusada

2022-10-29 18:45 UTC, LinaYahya approved these changes

2022-10-30 06:20 UTC, husamkamal requested changes
![Screenshot from 2022-10-30 08-19-09](https://user-images.githubusercontent.com/77546419/198865412-359489f5-bd02-4553-9225-8b3198037998.png)

if user not login and send request we should navigate them to login page

2022-10-30 06:27 UTC, husamkamal approved these changes

2022-10-30 07:02 UTC, abdou059 approved these changes

2022-10-30 07:19 UTC, mai-mohammed approved these changes

2022-10-30 07:20 UTC, merged