121 private routes
CA-G12/car-trade pull request #133
Opened 2022-10-31 12:20 UTC by abdou059

2022-10-31 19:19 UTC, LinaYahya requested changes
Great Job @abdou059

2022-10-31 19:19 UTC, LinaYahya commented on client/src/components/privateRoutes.tsx
> +function ProtectedRoute({ children, roles }:PrivateType) {
```suggestion
function ProtectedRoute({ children, roles }:PrivateType) {
```
Not sure what it's `roles` insteadof `role`

2022-10-31 19:19 UTC, LinaYahya commented on client/src/components/privateRoutes.tsx
> +import { useContext } from 'react';
This is not a component, move this file into routes folder

2022-11-01 08:37 UTC, mai-mohammed approved these changes

2022-11-01 08:45 UTC, LinaYahya approved these changes

2022-11-01 08:51 UTC, husamkamal approved these changes

2022-11-01 09:30 UTC, tariqabusada approved these changes

2022-11-01 09:30 UTC, merged