135 not found pages
CA-G12/car-trade pull request #136
Opened 2022-11-01 06:42 UTC by abdou059

2022-11-01 08:23 UTC, mai-mohammed approved these changes

2022-11-01 08:50 UTC, LinaYahya requested changes

2022-11-01 08:50 UTC, LinaYahya commented on client/src/pages/Errors/images.tsx
> +function Imag({ src, alt }:ImageProp) {
this is not `Imag` component, 
Basically this is a not found page

2022-11-01 10:48 UTC, husamkamal approved these changes

2022-11-02 08:49 UTC, LinaYahya approved these changes

2022-11-02 09:07 UTC, tariqabusada approved these changes

2022-11-02 09:08 UTC, merged