Send emails to the user
CA-G12/car-trade pull request #155
Opened 2022-11-03 01:36 UTC by mai-mohammed

**In this branch I do the following:**

- convert send email to reusable function.
- create an emails template 
- send an email when the user sends a sell request
- send an email to the user when his/her request is accepted.
- send an email to the user when his/her car is added to the market.

2022-11-03 08:29 UTC, LinaYahya commented on server/src/controllers/cars.ts
> +  if (process.env.NODE_ENV !== 'test') {
Well Done Mai

2022-11-03 08:36 UTC, LinaYahya requested changes

2022-11-03 08:36 UTC, LinaYahya commented on server/src/controllers/cars.ts
> + <button class="button">Go To Profile!</button>`;
```suggestion
 <button class="button">Go To Profile!</button>`;
```
This will not send me to profile, maybe we can have a link instead

2022-11-03 08:36 UTC, LinaYahya commented on server/src/controllers/cars.ts
> +    <button class="button">Go To Profile!</button>`;
use link instead

2022-11-03 08:40 UTC, husamkamal approved these changes

2022-11-03 08:41 UTC, abdou059 approved these changes

2022-11-06 07:59 UTC, tariqabusada approved these changes

2022-11-06 13:28 UTC, merged