build: images model
CA-G12/car-trade pull request #17
Opened 2022-10-12 10:39 UTC by mai-mohammed

add images model

2022-10-12 12:23 UTC, LinaYahya requested changes
keep `gitkeep`, delete file on folders that already have files

2022-10-12 12:32 UTC, husamkamal approved these changes

2022-10-12 13:37 UTC, abdou059 approved these changes

2022-10-12 20:37 UTC, tariqabusada commented on src/models/images.ts
> +    allowNull: false,
No need to use 'allowNull' property with 'primaryKey'

2022-10-12 20:40 UTC, tariqabusada commented on src/models/images.ts
> +  },
we need the 'carId' column

2022-10-13 05:21 UTC, abdou059 approved these changes

2022-10-13 07:31 UTC, LinaYahya approved these changes

2022-10-13 07:31 UTC, tariqabusada approved these changes

2022-10-13 07:40 UTC, merged