Fix Admin login style and make it responsive
CA-G12/car-trade pull request #190
Opened 2022-11-09 10:32 UTC by tariqabusada

2022-11-09 13:24 UTC, husamkamal approved these changes

2022-11-10 08:24 UTC, abdou059 requested changes

2022-11-10 08:24 UTC, abdou059 commented on client/src/pages/AdminLogin/styles.css
> +  height: 90vh;
why change height

2022-11-10 08:24 UTC, abdou059 commented on client/src/pages/AdminLogin/styles.css
> +  height: 90vh;
?

2022-11-10 10:53 UTC, tariqabusada commented on client/src/pages/AdminLogin/styles.css
> +  height: 90vh;
we need to hide scroll bar

2022-11-10 12:10 UTC, abdou059 approved these changes

2022-11-10 12:10 UTC, abdou059 approved these changes

2022-11-10 12:25 UTC, mai-mohammed approved these changes

2022-11-10 12:27 UTC, merged