build: car slider
CA-G12/car-trade pull request #57
Opened 2022-10-18 13:11 UTC by husamkamal

use react swiper to do slider

2022-10-18 13:13 UTC, abdou059 approved these changes

2022-10-18 13:13 UTC, mai-mohammed approved these changes

2022-10-18 19:05 UTC, tariqabusada approved these changes

2022-10-19 04:40 UTC, LinaYahya requested changes
I don't think this the style we want at the slider,
I believe no margin or white spaces should live within slider!

2022-10-19 08:47 UTC, merged