build: car detals
CA-G12/car-trade pull request #61
Opened 2022-10-19 07:55 UTC by abdou059

2022-10-19 08:28 UTC, mai-mohammed commented on server/src/controllers/cars/gitCarsId.ts
> +  const reus = await getCarById(id);
add validation on the result.

2022-10-19 08:29 UTC, husamkamal approved these changes

2022-10-19 08:29 UTC, tariqabusada approved these changes

2022-10-19 08:31 UTC, mai-mohammed commented on server/src/services/cars/getCar.ts
> +  const carId = await Car.findByPk(id);
rename this to result or car

2022-10-19 09:06 UTC, LinaYahya requested changes

2022-10-19 09:06 UTC, LinaYahya commented on server/src/services/cars/getCar.ts
> +  const carId = await Car.findByPk(id);
also include image model to get image for this car

2022-10-19 09:06 UTC, LinaYahya commented on server/src/routes/cars.ts
> +carsRouter.get('/cars/:id', ExpressWrapper(getCarsId));
```suggestion
carsRouter.get('/cars/:id', ExpressWrapper(getCarsById));
```

2022-10-19 09:06 UTC, LinaYahya commented on server/src/controllers/cars/index.ts
> +import getCarsId from './gitCarsId';
```suggestion
import getCarsId from './getCarsId';
```

2022-10-20 07:16 UTC, mai-mohammed approved these changes

2022-10-20 07:30 UTC, LinaYahya requested changes

2022-10-20 07:30 UTC, LinaYahya commented on server/__tests__/carsdetails.ts
> +import { describe, expect, test } from '@jest/globals';
beforeAll and afterAll required

2022-10-20 07:30 UTC, LinaYahya commented on server/src/controllers/cars/getCarsById.ts
> +  const { id } = req.params;
try to validate `id` to ensure it's a number, If not end response as a bad request

2022-10-20 09:05 UTC, LinaYahya approved these changes

2022-10-20 09:05 UTC, merged