66 handel search page
CA-G12/car-trade pull request #67
Opened 2022-10-20 09:48 UTC by husamkamal

2022-10-20 09:57 UTC, tariqabusada approved these changes

2022-10-20 09:58 UTC, abdou059 approved these changes

2022-10-20 10:05 UTC, mai-mohammed commented on client/src/components/CarCard/index.tsx
> +  milage,
mileage

2022-10-20 10:12 UTC, mai-mohammed approved these changes

2022-10-21 13:57 UTC, LinaYahya requested changes

2022-10-21 13:57 UTC, LinaYahya commented on client/src/components/CarsFilter/index.tsx
> +    setLoading(true);
setLoading to true inside getCars, As I gurantee that loading set to true when request is about to send

2022-10-21 13:57 UTC, LinaYahya commented on client/src/components/CarsFilter/index.tsx
> +      const response: CarsData = await httpInstance.get('/cars?', { params });
What if there's an error!
create try and catch block and create an error state if there's an error, maybe we can use a snackbar component to tell the user that there's unexpected error

2022-10-21 13:57 UTC, LinaYahya commented on client/src/components/CarsFilter/index.tsx
>      <section className="filter">
change the default value for brand to `=defaultValue={state?.brand || null}` as the autocomplete doesn't expect to receive an empty string as a default value

2022-10-21 13:57 UTC, LinaYahya commented on client/src/helpers/skeleton.tsx
> +    <div
move this to the components folder,  any try to change the style to be more closer to the car card component

2022-10-21 13:57 UTC, LinaYahya commented on client/src/pages/Cars/index.tsx
> +    <h1>sd</h1>
this folder should be the search page, SO use one of them either this or the search!

2022-10-21 13:57 UTC, LinaYahya commented on client/src/pages/Search/index.tsx
> +                  e.images[0]?.image || 'https://thumbs.dreamstime.com/b/no-image-available-icon-photo-camera-flat-vector-illustration-132483141.jpg'
notice that the car width for the components doesn't have images is not the same for others, So try to fix style to give all cards the same width so they will be aligned together at the container

2022-10-21 13:57 UTC, LinaYahya commented on client/src/pages/Search/index.tsx
> +                count={pagination / 9}
use  `ceil` here

2022-10-21 13:57 UTC, LinaYahya commented on client/src/pages/Search/index.tsx
> +          ) : <h2 style={{ fontSize: '2rem' }}>NO results found</h2>)}
create a custom component for no results

2022-10-21 13:57 UTC, LinaYahya commented on client/src/pages/Search/index.tsx
> +  const [pageNumber, setPageIndex] = useState<number>(1);
```suggestion
  const [currentPage, setCurrentPAge] = useState<number>(1);
```
use meaningful, descriptive names

2022-10-23 08:27 UTC, LinaYahya approved these changes

2022-10-23 08:28 UTC, merged