add car info section
CA-G12/car-trade pull request #68
Opened 2022-10-20 13:01 UTC by mai-mohammed

- add a car information component + styles.

2022-10-21 14:19 UTC, LinaYahya requested changes
Not sure WHy there are 38 Files changes! 😢 
Great Job May!

2022-10-21 14:19 UTC, LinaYahya commented on client/src/components/CarInfoSection/index.tsx
> +      <section className="buttons-container">
Not sure, But maybe It will look better if the buttons were inside the card, 
What do you think?

2022-10-21 14:19 UTC, LinaYahya commented on client/src/components/CarInfoSection/index.tsx
> +        </section>
there's a possibility that thesr's no description for specific card, try to handle this section conditionally

2022-10-21 15:18 UTC, mai-mohammed commented on client/src/components/CarInfoSection/index.tsx
> +      <section className="buttons-container">
I will try to do that + the 38 files changed because of the error that occurred when I pulled the main branch and tried to resolve the conflict, I will see how to solve that also.

2022-10-21 19:46 UTC, tariqabusada approved these changes

2022-10-23 05:52 UTC, LinaYahya approved these changes

2022-10-23 06:43 UTC, husamkamal approved these changes

2022-10-23 06:46 UTC, merged