78 update car
CA-G12/car-trade pull request #79
Opened 2022-10-23 13:11 UTC by husamkamal

2022-10-23 18:14 UTC, LinaYahya requested changes

2022-10-23 18:14 UTC, LinaYahya commented on client/src/pages/Cars/index.tsx
> +  console.log(cars, 'cars');
```suggestion
```

2022-10-23 18:14 UTC, LinaYahya commented on .github/workflows/node.js.yml
> +          SECRET_KEY: car-trade-secret-123456
I'll put both secret key and tokens as repository secrets,
Check How to import them [encrypted secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets)

2022-10-23 18:14 UTC, LinaYahya commented on server/__tests__/cars.ts
> +      .set('Cookie', 'token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VySWQiOjF9.5bbTDHhlnCvs5ZDGfXcL_MU_4CCKzJ61wUDCGD_nWks');
put on env and import from there, 
Also I've put it as a repo secret as `ADMIN_TOKEN`

2022-10-23 18:14 UTC, LinaYahya commented on server/src/controllers/cars/updateCars.ts
> +  });
Why you do this, if there as an error it'll be thrown to `RouterWraper` where we handle validation error

2022-10-23 18:14 UTC, LinaYahya commented on server/src/helpers/updateCarSchema.ts
> +import * as yup from 'yup';
We already have a validation folder

2022-10-23 18:14 UTC, LinaYahya commented on server/__tests__/cars.ts
> +  test('should return id of car that update', async () => {
create more tests in case of token was malformed, or where is no token

2022-10-23 18:14 UTC, LinaYahya commented on server/__tests__/cars.ts
> +    expect(result.statusCode).toEqual(200);
Is that a real test!!
Where's request body?

2022-10-23 18:14 UTC, LinaYahya commented on server/src/helpers/updateCarSchema.ts
> +
What about state and fuel, validate them according to options we have

2022-10-23 18:14 UTC, LinaYahya commented on server/src/services/cars/updateCar.ts
> +  console.log(car);
```suggestion
```

2022-10-23 18:14 UTC, LinaYahya commented on server/src/controllers/cars/updateCars.ts
> +  return { status: 200, msg: 'done!', data: result };
```suggestion
  return { status: 200, msg: 'done!', data: result }; // not sure if we want to return count of rows updated, No need I guess
```

2022-10-24 06:08 UTC, abdou059 approved these changes

2022-10-24 07:41 UTC, LinaYahya requested changes

2022-10-24 07:41 UTC, LinaYahya commented on server/src/validation/updateCarSchema.ts
> +  state: yup.string().notRequired().label('state'),
state here accept any value is it's only required, But we need to validate value to be one the options allowed,
Check `Yup.oneof()`,
The same for fuel

2022-10-24 07:41 UTC, LinaYahya commented on server/src/controllers/cars/updateCars.ts
> +  return { status: 200, msg: 'done!', data: result };
Not sure if it is resolved!

2022-10-24 07:48 UTC, LinaYahya requested changes

2022-10-24 07:48 UTC, LinaYahya commented on server/src/validation/updateCarSchema.ts
> +import * as yup from 'yup';
export to `validation/index` and import from there

2022-10-24 08:24 UTC, LinaYahya approved these changes

2022-10-24 08:26 UTC, mai-mohammed approved these changes

2022-10-24 08:45 UTC, merged