fix: delete cars
CA-G12/car-trade pull request #81
Opened 2022-10-24 06:07 UTC by abdou059

2022-10-24 06:19 UTC, LinaYahya requested changes

2022-10-24 06:19 UTC, LinaYahya commented on server/tsconfig.json
> +      "target": "es2017",
Why is that?

2022-10-24 06:19 UTC, LinaYahya commented on server/src/routes/cars.ts
> +carsRouter.delete('/cars/:id', ExpressWrapper(deleteCarsById));
this route is protected, only admin can delete the car

2022-10-24 06:19 UTC, LinaYahya commented on server/src/services/cars/deleteCar.ts
> +      id,
What if id isn't a number, what if there's no car with this id

2022-10-24 06:19 UTC, LinaYahya commented on server/src/controllers/cars/deleteCarsById.ts
> +  const del = await deleteCars(id);
no need to return anything

2022-10-24 11:38 UTC, LinaYahya approved these changes

2022-10-24 12:23 UTC, mai-mohammed approved these changes

2022-10-24 12:27 UTC, LinaYahya approved these changes

2022-10-25 09:10 UTC, husamkamal approved these changes

2022-10-25 10:39 UTC, merged