refactor: form for send request from the customer
CA-G12/car-trade pull request #84
Opened 2022-10-24 09:49 UTC by tariqabusada

- Edited send request form component to be able to convert mileage from Mile to KM
- Added price, year and mileage input fields type number.

2022-10-25 11:33 UTC, LinaYahya approved these changes

2022-10-25 13:16 UTC, abdou059 approved these changes

2022-10-26 07:17 UTC, mai-mohammed approved these changes

2022-10-26 07:33 UTC, husamkamal commented on client/src/components/sendRequsetModel/Form.tsx
>        console.log(values);
remove conole.log

2022-10-26 07:37 UTC, husamkamal requested changes

2022-10-26 07:37 UTC, husamkamal commented on client/src/components/sendRequsetModel/Form.tsx
>        alert(JSON.stringify(values, null, 2));
remove alert

2022-10-26 13:28 UTC, husamkamal approved these changes

2022-10-26 13:28 UTC, merged