82 login backend
CA-G12/car-trade pull request #86
Opened 2022-10-24 11:39 UTC by husamkamal

2022-10-24 11:56 UTC, mai-mohammed approved these changes

2022-10-24 12:24 UTC, LinaYahya requested changes

2022-10-24 12:24 UTC, LinaYahya commented on server/src/helpers/passwordCompare.ts
> +    bcrypt.compare(password, hash, (err, res) => {
```suggestion
    bcrypt.compare(password, hash, (err, res) => {
```
// no need to convert to promise as bcrypt supports promise by nature

2022-10-24 12:24 UTC, LinaYahya commented on server/src/helpers/generateToken.ts
> +      { role: 'user', payload },
```suggestion
      payload,
```
SO we can use `generateToken` to both admin and user auth

2022-10-24 12:24 UTC, LinaYahya commented on server/src/helpers/generateToken.ts
> +  const tokenGenerate = new Promise((resolve, reject) => {
```suggestion
const generateToken = (payload) => new Promise((resolve, reject) => {
```
return in one line

2022-10-24 12:24 UTC, LinaYahya commented on server/src/services/login.ts
> +const loginServices = async ({ email }) => {
no need to create a service, or use descriptive meaning

2022-10-24 12:24 UTC, LinaYahya commented on server/src/controllers/login.ts
> +  if (!result?.password.length) {
```suggestion
  if (!result) { // why to check on password specifically, result will be null if there's no user 
```

2022-10-24 12:24 UTC, LinaYahya commented on server/src/controllers/login.ts
> +    return { status: 200, msg: 'done', data: { msg: 'user not found' } };
```suggestion
    throw createErr(400, )
```

2022-10-25 07:17 UTC, LinaYahya approved these changes

2022-10-25 07:17 UTC, LinaYahya approved these changes

2022-10-25 07:19 UTC, abdou059 approved these changes

2022-10-25 07:23 UTC, merged