build: create send request admin module sepper
CA-G12/car-trade pull request #93
Opened 2022-10-25 11:52 UTC by husamkamal

Relates #92

add module to to-check table that module make admin able to send car request and make this mudle stepper

2022-10-25 13:21 UTC, abdou059 approved these changes

2022-10-25 18:34 UTC, LinaYahya requested changes

2022-10-25 18:34 UTC, LinaYahya commented on client/src/components/stepper.tsx
> +            <StepContent>{component}</StepContent>
```suggestion
            <StepContent>{component}</StepContent> // try to render a div here, actually this is not the place to render our forms
```

2022-10-26 08:58 UTC, LinaYahya approved these changes

2022-10-27 04:22 UTC, mai-mohammed approved these changes

2022-10-27 04:22 UTC, mai-mohammed commented on client/src/components/stepper.tsx
> +const steps = ['Car Into', 'Car Image'];
info

2022-10-27 04:23 UTC, merged