build: functionality for send selling request
CA-G12/car-trade pull request #96
Opened 2022-10-25 22:05 UTC by tariqabusada

- rearrange server files
- create 'addCar' function in controllers
- create 'addCarService' function in services
- create fetch in client side to send the request to server
- create route to run the middlewares

2022-10-26 07:24 UTC, abdou059 commented on client/src/routes/index.tsx
> -// import Cars from '../pages/Cars';
remove comment

2022-10-26 08:17 UTC, LinaYahya requested changes

2022-10-26 08:17 UTC, LinaYahya commented on server/src/validation/updateCarSchema.ts
> +  customerId: yup.number().notRequired().label('customerId'),
not sure why you added `customerId` here?

2022-10-26 08:17 UTC, LinaYahya commented on server/src/services/cars/addCar.ts
> +  const carRequest = await Car.bulkCreate(
bulk create used to insert more than a row to db, But we're not doing that right now,
check `Model.create`

2022-10-26 08:17 UTC, LinaYahya commented on server/src/routes/cars.ts
> +// carsRouter.get('/profile/sell', authMiddleware('user'), ExpressWrapper(addCar));
not sure where's the route?

2022-10-26 08:17 UTC, LinaYahya commented on server/src/controllers/cars/addCar.ts
> +  const customerId = req.cookies.id;
```suggestion
  const customerId = req.cookies.id; 
```
DO we have `id` at `cookies`?

2022-10-26 08:17 UTC, LinaYahya commented on server/src/controllers/cars/addCar.ts
> +  await updateCarSchema.validate(body, customerId);
```suggestion
  await updateCarSchema.validate(body, customerId);
```
Does validate accept two params?

2022-10-27 11:38 UTC, husamkamal commented on client/src/components/sendRequsetModel/Form.tsx
> +      // console.log(values);
remove

2022-10-27 11:38 UTC, husamkamal commented on server/src/controllers/cars/addCar.ts
> +  // const { token } = req.cookies;
remove

2022-10-27 11:51 UTC, LinaYahya requested changes

2022-10-27 11:51 UTC, LinaYahya commented on server/src/services/cars/addCar.ts
> +const addCarService = async (body, id) => {
```suggestion
const addCarService = async (data) => { // {...body, customerId}
```

2022-10-27 11:51 UTC, LinaYahya commented on server/src/services/cars/addCar.ts
> +  const carRequest = await Car.create(
```suggestion
  const car = await Car.create(
```
It's only  a car

2022-10-27 11:51 UTC, LinaYahya commented on server/src/routes/cars.ts
> +carsRouter.post('/sell-car', authMiddleware('user'), ExpressWrapper(addCar));
```suggestion
carsRouter.post('/', authMiddleware('user'), ExpressWrapper(addCar));
```
it's not a good practice to have a resource name that include the method,
request method `post` will definitely means it's add

2022-10-27 11:51 UTC, LinaYahya commented on server/src/controllers/cars/addCar.ts
> +  return { message: 'successfully', status: 200, data: result };
```suggestion
  return { message: 'successfully', status: 201, data: result };
```

2022-10-27 11:51 UTC, LinaYahya commented on client/src/components/sendRequsetModel/Form.tsx
> +        });
here we need to handle `loading`, and `success mesaage` and `error message`

2022-10-27 12:17 UTC, husamkamal approved these changes

2022-10-27 13:05 UTC, LinaYahya approved these changes

2022-10-27 13:30 UTC, abdou059 approved these changes

2022-10-27 13:31 UTC, husamkamal approved these changes

2022-10-27 13:33 UTC, mai-mohammed approved these changes

2022-10-27 13:33 UTC, merged