dashbord requests
CA-G12/car-trade pull request #98
Opened 2022-10-26 08:54 UTC by mai-mohammed

2022-10-26 10:07 UTC, LinaYahya requested changes
- change requestTable import at components/tabs as follows `import RequestsTable from '../requestsTable'; file name as `requestTable` 
- give `requestSkelton` key

2022-10-26 10:07 UTC, LinaYahya commented on client/src/pages/Cars/index.tsx
> +import CustomSkeleton from '../../components/skeletons/skeleton';
rename file So I'll understand that this a dashboard skeleton

2022-10-26 10:07 UTC, LinaYahya commented on client/src/components/skeletons/tableSkeleton.tsx
> +/* eslint-disable react/jsx-closing-tag-location */
```suggestion
```
Fix eslint error instead of disabling it

2022-10-26 10:07 UTC, LinaYahya commented on client/src/components/requestsTable/row.tsx
> +type Props = { car:CarWithCustomerInfo, state:string,
move to interfaces file

2022-10-26 10:07 UTC, LinaYahya commented on client/src/components/requestsTable/row.tsx
> +  const handleReject = async (id:number) => {
```suggestion
  const deleteCar = async (id:number) => {
```

2022-10-26 10:07 UTC, LinaYahya commented on client/src/components/requestsTable/row.tsx
> +      setSnackbarMessage('Reject request successfully');
give it a descriptive and clear message

2022-10-26 10:07 UTC, LinaYahya commented on client/src/components/requestsTable/row.tsx
> +      setSnackbarMessage('Reject request successfully');
as you can see thers's too many states for `SnackBar`, maybe we can combine them in one state as follows
```js
  const [snackbar, setSnackbar = useState({isOpen, msg, type});
```

2022-10-26 11:55 UTC, LinaYahya approved these changes

2022-10-26 13:10 UTC, husamkamal commented on client/src/components/RequestsTable/index.tsx
> +  const [page, setPage] = useState<number>(1);
const [currentPage, setCurrentPage] = useState<number>(1);

2022-10-26 13:15 UTC, husamkamal commented on client/src/components/RequestsTable/index.tsx
> +        setPageCount(Math.floor(response.data.count / 10));
I don`t know floor what to do but I prefer to use clie search it

2022-10-26 13:19 UTC, husamkamal commented on client/src/components/RequestsTable/row.tsx
> +      setCarsData((prevState) => prevState.filter(((element) => element.id !== car.id)));
why put car.id       setCarsData((prevState) => prevState.filter(((element) => element.id !== car.id)));
you already have car id as parameter here  const deleteCar = async (id:number) => {
 setCarsData((prevState) => prevState.filter(((element) => element.id !==  id)));

2022-10-26 13:20 UTC, husamkamal commented on client/src/components/RequestsTable/row.tsx
> +      setCarsData((prevState) => prevState.filter(((element) => element.id !== car.id)));
same delete

2022-10-26 13:27 UTC, husamkamal requested changes
![Screenshot from 2022-10-26 16-23-23](https://user-images.githubusercontent.com/77546419/198037480-ae920dd7-8d0d-48a9-a36c-df0e999249e3.png)

key props

2022-10-27 06:55 UTC, husamkamal approved these changes

2022-10-27 07:02 UTC, abdou059 approved these changes

2022-10-27 07:02 UTC, merged