97 context provider
CA-G12/car-trade pull request #99
Opened 2022-10-26 12:21 UTC by husamkamal

CLOSE: #97 
task :
1 - create context file
- create /user endpoint backend 
- add provider to app

2022-10-26 12:57 UTC, LinaYahya approved these changes

2022-10-26 13:08 UTC, abdou059 approved these changes

2022-10-27 06:16 UTC, mai-mohammed requested changes

2022-10-27 06:16 UTC, mai-mohammed commented on server/src/controllers/user.ts
> +  if (token) {
you should handle admin case

2022-10-27 06:26 UTC, mai-mohammed approved these changes

2022-10-27 06:27 UTC, merged